### ISSUE TITLE
Analysing the FDK cuda code

### ISSUE THREAD

**Issue by BieberleA** [hzdr/PARIS#33]
As Matthias is currently Jan's supervisor from ZiH (TU Dresden) side, I asked him (and Stephan Boden too) to analyze the current code and to propose enhancements if necessary. Let's go!

**Comment by tdd11235813** [comment]
just want to drop a message here that I am looking forward to profile the GPU code :)
If data is required to run the code we can use our GCOE project on the GPU cluster Taurus to share the data and results. I am going to invite @j-stephan to that project.
I assume that you are still in development, just let me know when code is ready to be profiled.

**Comment by BieberleA** [comment]
Matthias, there is already a stable version: 0.2.0 that can be profiled, isn't it Jan?

**Comment by j-stephan** [comment]
Sorry for the late response, I'm currently focused on my last (written) exam of my student career. Starting on Wednesday I will finally have the time to work on PARIS again.

Matthias should be able to profile version 0.2.0 if he'd like to. However, I plan to integrate some minor CUDA optimizations on Wednesday. It would be interesting to compare the two versions.

**Comment by juckel** [comment]
This popped up as a open issue when I connect GitHub to our Mattermost. I believe this can be closed. @BieberleA do you agree?

**Comment by BodenS** [comment]
From my side it's ok.
